### ISSUE TITLE
Lectern types interferes with Cured Villager Profession swap. ( I think? )

### ISSUE THREAD

**Issue by Gbergz** [Yanis48/FabriBlocks#5]
[1.14.4] Title^ Changing to any other profession works. Not the lectern one tho. Maybe it has something to do with the name swap? to Oak Lectern instead of just Lectern.

**Comment by YanisBft** [comment]
Hum it works fine for me, villagers become librarian when using vanilla lecterns. Using FabriBlocks lecterns (other woods than oak) won't work though ^^

**Comment by Gbergz** [comment]
Did you spawn your villager through a spawn egg? I tried that and it did not work. Curing a Zombie Villager with Splash potion of weakness then right clicking with a normal Golden Apple will cure it, wait a couple of minutes and then try changing profession. Didn't work for me.. sadly. I'm playing AOF version 4.0.1

**Comment by YanisBft** [comment]
I don't think your bug is related to my mod :/ There are mods changing villager behavior in this modpack, more chance it's coming from them

**Comment by Gbergz** [comment]
You're probably right yes, sorry for the unnecessary issue-report.
